### ISSUE TITLE
Please rename `redo` to `redo.plugin.zsh`

### ISSUE THREAD

**Issue by unixorn** [joknarf/redo#3]
If you rename `redo` to `redo.plugin.zsh`, then ZSH plugin managers like [zgenom](https://github.com/jandamm/zgenom), [prezto](https://github.com/sorin-ionescu/prezto), or any others that conform to the [ZSH plugin standard](https://zdharma-continuum.github.io/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html) can automatically load it when this repository is added to their plugin list.

**Comment by joknarf** [comment]
Hello, I'm not very familiar with zsh plugins, and I'am not sure the code will fit directly with ZSH plugins standard, as the code is here zsh/bash compatible.
Maybe I should study the zsh plugins standard, and make a dedicated zsh repository with proper format.
If you like redo, I think you can take a look at [cdhist](https://github.com/joknarf/cdhist) , which uses the same approach (with Esc-! default hotkey) based on [selector](https://github.com/joknarf/selector) menu.

**Comment by unixorn** [comment]
If it works when you source the file in ZSH, it should work with a framework, they basically just automate sourcing all your plugin files.

**Comment by unixorn** [comment]
If you want to test it with a framework, I recommend [zgenom](https://github.com/jandamm/zgenom).

**Comment by joknarf** [comment]
> If you want to test it with a framework, I recommend [zgenom](https://github.com/jandamm/zgenom).

ok, thank you Joe. I will try that.

**Comment by joknarf** [comment]
I added a link to redo with name `redo.plugin.zsh`, now you can use `zgenom load joknarf/redo`
